name: DocBinder OSS Library CI/CD

on:
  push:
    branches:
      - main
      - dev
    paths:
      - "docbinder-oss/**"
  pull_request:
    paths:
      - "docbinder-oss/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel tox
          cd docbinder-oss
          pip install -r requirements.txt || true
          pip install tox

      - name: Run tests
        run: |
          cd docbinder-oss
          tox

      - name: upload windows dists
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

  pypi-publish:
    runs-on: ubuntu-latest
    needs:
      - test
    if: github.ref == 'refs/heads/main'
    permissions:
      id-token: write
    environment:
      name: pypi
      url: https://pypi.org/p/DocBinder-OSS

    steps:
      - name: build release distributions
        run: |
          # NOTE: put your own distribution build steps here.
          python -m pip install build
          python -m build

      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@v1.12.4
